# tools/data/biology_part2.py
# Authentic NCERT Biology Catalog - Remaining Class 11 (11 to 19) & All Class 12 (1 to 13)

BIOLOGY_PART2 = {
    # BIO-11-11: Photosynthesis in Higher Plants
    "BIO-11-11": [
        {
            "title": "Light Reactions, Chemiosmosis, Calvin C3 & C4 Pathways",
            "desc": "Photosynthetic pigments, Z-scheme photophosphorylation (cyclic and non-cyclic), photolysis of water, Mitchell's chemiosmotic ATP synthesis, Calvin cycle (C3 pathway, RuBisCO), Hatch-Slack C4 pathway (Kranz anatomy, PEPcase), and photorespiration.",
            "notesOverview": "Photosynthesis converts radiant solar energy into stable chemical bonds. Light reactions generate ATP and NADPH via thylakoid proton gradients, powering stromal dark enzymatic carbon fixation.",
            "notesSections": [
                {
                    "heading": "Photophosphorylation and Carbon Fixation Pathways",
                    "paragraphs": [
                        "Light Reactions (Z-Scheme): PS II (P680) absorbs 680 nm light, passes electrons through pheophytin, PQ, cytochrome b6f, PC to PS I (P700), generating NADPH + H+. Water splitting complex associated with PS II on inner thylakoid surface releases O2: 2 H2O -> 4 H+ + 4 e- + O2.",
                        "Chemiosmotic Hypothesis (Peter Mitchell): Proton accumulation inside the thylakoid lumen creates a proton gradient (Delta pH). Protons flow through CF0-CF1 ATP synthase channels into stroma, synthesizing ATP.",
                        "Calvin Cycle (C3): Carboxylation (CO2 + RuBP -> 2 x 3-PGA by RuBisCO) -> Reduction (consumes 2 ATP + 2 NADPH per CO2) -> Regeneration (consumes 1 ATP). Net for 1 Glucose (6 CO2): 18 ATP + 12 NADPH.",
                        "C4 Pathway (Hatch-Slack): Kranz anatomy (mesophyll cells lack RuBisCO, possess PEP carboxylase; bundle sheath cells have RuBisCO, agranal chloroplasts). Primary CO2 acceptor is PEP (3C) forming OAA (4C). Avoids photorespiratory oxygenation losses, optimal at high temperatures."
                    ],
                    "keyTakeaways": [
                        "RuBisCO is the most abundant enzyme on Earth, possessing both carboxylase and oxygenase activity.",
                        "In C4 plants, photorespiration is completely absent because CO2 concentration at RuBisCO active sites is kept high by C4 acid decarboxylation."
                    ],
                    "examTips": ["Synthesis of 1 glucose molecule in C3 plants requires 18 ATP and 12 NADPH; in C4 plants it requires 30 ATP and 12 NADPH (12 extra ATP for PEP regeneration)."]
                }
            ],
            "misconceptions": ["Assuming dark reactions occur only at night. 'Dark reactions' are light-independent enzymatic reactions that occur continuously in daylight utilizing ATP and NADPH generated by light reactions."],
            "formulas": [
                {
                    "label": "Calvin Cycle Stoichiometry per Glucose",
                    "formula": "6\\text{CO}_2 + 18\\text{ATP} + 12\\text{NADPH} \\longrightarrow \\text{C}_6\\text{H}_{12}\\text{O}_6 + 18\\text{ADP} + 18\\text{P}_i + 12\\text{NADP}^+",
                    "description": "Net biochemical energetic input required for single hexose glucose synthesis in C3 photosynthesis.",
                    "variables": [
                        { "symbol": "\\text{CO}_2", "meaning": "Carbon Dioxide Fixed", "unit": "mol" },
                        { "symbol": "\\text{ATP}", "meaning": "Adenosine Triphosphate Consumed", "unit": "mol" }
                    ]
                }
            ]
        }
    ],

    # BIO-11-12: Respiration in Plants
    "BIO-11-12": [
        {
            "title": "Glycolysis, Krebs Cycle, Electron Transport & Respiratory Quotient",
            "desc": "Cellular respiration, Glycolysis (EMP pathway), fermentation, aerobic respiration, TCA / Krebs cycle in mitochondrial matrix, Electron Transport System (ETS) complexes I-IV, oxidative phosphorylation, and Respiratory Quotient (RQ = CO2 evolved / O2 consumed).",
            "notesOverview": "Cellular respiration breaks down organic substrates to release energy trapped as ATP. Glycolysis in the cytoplasm feeds pyruvate into mitochondrial Krebs cycle and oxidative phosphorylation.",
            "notesSections": [
                {
                    "heading": "Glycolytic Substrate Oxidation and ETS ATP Yield",
                    "paragraphs": [
                        "Glycolysis (EMP Pathway): Occurs in cytoplasm of all living cells. 1 Glucose (6C) -> 2 Pyruvate (3C). Consumes 2 ATP; generates 4 ATP + 2 NADH (net gain = 2 ATP + 2 NADH). Rate-limiting step is catalyzed by phosphofructokinase (PFK).",
                        "Link Reaction: Pyruvate enters mitochondrial matrix: Pyruvate + CoA + NAD+ -> Acetyl CoA + CO2 + NADH + H+ (catalyzed by pyruvate dehydrogenase).",
                        "Krebs Cycle (TCA): Acetyl CoA (2C) condenses with OAA (4C) to form Citrate (6C). Per Acetyl CoA turn: 3 NADH, 1 FADH2, 1 GTP, 2 CO2. Per Glucose (2 turns): 6 NADH, 2 FADH2, 2 GTP.",
                        "ETS Complexes: Complex I (NADH dehydrogenase), Complex II (Succinate dehydrogenase), Complex III (Cytochrome bc1), Complex IV (Cytochrome c oxidase with Cu centers). Terminal electron acceptor is molecular oxygen O2 forming H2O.",
                        "Net ATP Yield: Oxidation of 1 NADH yields 3 ATP (or 2.5); 1 FADH2 yields 2 ATP (or 1.5). Total theoretical net yield per glucose is 36 or 38 ATP.",
                        "Respiratory Quotient (RQ = CO2 / O2): Carbohydrates = 1.0; Fats (tripalmitin) = 0.7; Proteins = 0.9; Organic acids (malic acid) > 1.0; Anaerobic respiration = infinity."
                    ],
                    "keyTakeaways": [
                        "Cytochrome c is a small, mobile electron-carrier protein attached to the outer surface of the inner mitochondrial membrane.",
                        "Respiratory pathway is amphibolic (involves both catabolism and anabolism of precursors)."
                    ],
                    "examTips": ["In fermentation, only less than 7% of total energy in glucose is released, and yeast poisons itself to death when alcohol concentration reaches approximately 13%."]
                }
            ],
            "misconceptions": ["Believing respiration in plants occurs only in the absence of light. Respiration occurs continuously 24 hours a day in all living plant cells."],
            "formulas": [
                {
                    "label": "Respiratory Quotient (RQ)",
                    "formula": "\\text{RQ} = \\frac{\\text{Volume of } \\text{CO}_2 \\text{ evolved}}{\\text{Volume of } \\text{O}_2 \\text{ consumed}}, \\quad \\text{RQ}_{\\text{tripalmitin}} = \\frac{102 \\, \\text{CO}_2}{145 \\, \\text{O}_2} \\approx 0.7",
                    "description": "Ratio of carbon dioxide released to oxygen consumed during aerobic substrate oxidation.",
                    "variables": [
                        { "symbol": "\\text{RQ}", "meaning": "Respiratory Quotient", "unit": "-" }
                    ]
                }
            ]
        }
    ],

    # BIO-11-13: Plant Growth and Development
    "BIO-11-13": [
        {
            "title": "Phytohormones: Auxins, Gibberellins, Cytokinins, Ethylene & ABA",
            "desc": "Characteristics of plant growth, differentiation, dedifferentiation, redifferentiation, plant growth regulators (PGRs): Auxins (apical dominance), Gibberellins (bolting), Cytokinins (cell division, delay of senescence), Ethylene (fruit ripening), Abscisic acid (stress hormone), and photoperiodism.",
            "notesOverview": "Plant development integrates intrinsic genetic programs with extrinsic environmental stimuli (light, gravity) mediated by phytohormone signaling cascades.",
            "notesSections": [
                {
                    "heading": "Phytohormone Functions and Developmental Responses",
                    "paragraphs": [
                        "Auxins (IAA, NAA, 2,4-D): Promote apical dominance (inhibition of lateral buds), root initiation in stem cuttings, parthenocarpy in tomatoes, and selective dicot weedicide (2,4-D).",
                        "Gibberellins (GA3): Promote stem elongation in rosetting plants ('bolting' in cabbage, beet), break seed dormancy, increase stalk length in grapes, and hasten malting in brewing.",
                        "Cytokinins (Kinetin, Zeatin): Promote cytokinesis, overcome apical dominance, delay leaf senescence (Richmond-Lang effect) by promoting nutrient mobilization.",
                        "Ethylene (Gaseous PGR): Promotes horizontal growth of seedlings, fruit ripening (climacteric rise in respiration), breaks seed/bud dormancy, and promotes root hair growth.",
                        "Abscisic Acid (ABA): 'Stress hormone', closes stomata during drought, induces seed dormancy, acts as a general plant growth inhibitor antagonistic to gibberellins."
                    ],
                    "keyTakeaways": [
                        "Differentiation: Meristematic cells mature to perform specific functions (loss of division).",
                        "Dedifferentiation: Mature living cells regain division capacity under specific conditions (e.g. formation of interfascicular cambium and cork cambium from parenchyma)."
                    ],
                    "examTips": ["Antagonistic hormone pairs: Auxin promotes apical dominance vs Cytokinin promotes lateral bud growth; Gibberellin breaks seed dormancy vs ABA induces seed dormancy."]
                }
            ],
            "misconceptions": ["Assuming ABA is harmful because it inhibits growth. ABA is vital for plant survival, acting as an emergency stress hormone that closes stomata during water deficit."],
            "formulas": [
                {
                    "label": "Geometric vs Arithmetic Growth Equations",
                    "formula": "L_t = L_0 + r t \\; (\\text{Arithmetic}), \\quad W_1 = W_0 e^{r t} \\; (\\text{Geometric Exponential})",
                    "description": "Mathematical models describing linear arithmetic vs exponential geometric cell growth.",
                    "variables": [
                        { "symbol": "L_t, W_1", "meaning": "Length / Biomass at Time t", "unit": "-" },
                        { "symbol": "r", "meaning": "Relative Growth Rate", "unit": "s^{-1}" }
                    ]
                }
            ]
        }
    ],

    # BIO-11-14: Breathing and Exchange of Gases
    "BIO-11-14": [
        {
            "title": "Respiratory Capacities, Gas Transport & Oxygen Dissociation Curve",
            "desc": "Human respiratory anatomy, mechanism of breathing (Boyle's law), respiratory volumes and capacities (TV, IRV, ERV, RV, VC, TLC), gas exchange across alveolar membrane, oxygen-hemoglobin dissociation curve, Bohr effect, transport of CO2, and neural regulation of respiration.",
            "notesOverview": "Gas exchange occurs across the thin alveolar membrane via simple diffusion driven by partial pressure gradients. Hemoglobin transports oxygen cooperatively, modulated by pH, CO2, and temperature.",
            "notesSections": [
                {
                    "heading": "Pulmonary Capacities and Gas Transport Mechanisms",
                    "paragraphs": [
                        "Respiratory Volumes: Tidal Volume (TV = 500 mL); Inspiratory Reserve Volume (IRV = 2500-3000 mL); Expiratory Reserve Volume (ERV = 1000-1100 mL); Residual Volume (RV = 1100-1200 mL, cannot be expelled).",
                        "Capacities: Vital Capacity (VC = TV + IRV + ERV = 3500-4500 mL); Total Lung Capacity (TLC = VC + RV = 5000-6000 mL). RV and TLC cannot be measured by simple spirometry.",
                        "Oxygen Transport: 97% transported bound to hemoglobin (oxyhemoglobin, Hb4(O2)4); 3% dissolved in plasma. Each gram of Hb binds 1.34 mL of O2.",
                        "Oxygen Dissociation Curve (Sigmoid): Shifts to the RIGHT (Bohr effect: favors O2 unloading at tissues) by: high pCO2, low pH (high H+), high temperature, and high 2,3-DPG.",
                        "Carbon Dioxide Transport: 70% as bicarbonate ions (HCO3^-) mediated by RBC carbonic anhydrase; 20-25% as carbaminohemoglobin; 7% dissolved in plasma. Chloride shift (Hamburger phenomenon) maintains RBC ionic balance."
                    ],
                    "keyTakeaways": [
                        "Respiratory rhythm center is located in the medulla oblongata; pneumotaxic center in the pons moderates rhythm.",
                        "Chemosensitive receptors near medulla are sensitive to CO2 and H+ concentrations, NOT to oxygen levels."
                    ],
                    "examTips": ["Every 100 mL of oxygenated blood delivers approximately 5 mL of O2 to tissues under normal conditions; every 100 mL of deoxygenated blood delivers 4 mL of CO2 to alveoli."]
                }
            ],
            "misconceptions": ["Believing blood oxygen levels regulate normal breathing. The primary physiological driver of human ventilation is arterial pCO2 and H+ concentration, not pO2."],
            "formulas": [
                {
                    "label": "Vital Capacity and Lung Volumes",
                    "formula": "\\text{VC} = \\text{TV} + \\text{IRV} + \\text{ERV}, \\quad \\text{TLC} = \\text{VC} + \\text{RV}",
                    "description": "Standard diagnostic partitioning of total lung capacity into spirometric volumes.",
                    "variables": [
                        { "symbol": "\\text{VC}", "meaning": "Vital Capacity", "unit": "mL" },
                        { "symbol": "\\text{TV}", "meaning": "Tidal Volume (500 mL)", "unit": "mL" },
                        { "symbol": "\\text{RV}", "meaning": "Residual Volume (1200 mL)", "unit": "mL" }
                    ]
                }
            ]
        }
    ],

    # BIO-11-15: Body Fluids and Circulation
    "BIO-11-15": [
        {
            "title": "Cardiac Cycle, ECG, Double Circulation & Blood Groups",
            "desc": "Blood components (plasma, RBCs, WBCs, platelets), ABO and Rh blood groups, erythroblastosis fetalis, blood clotting cascade, human heart anatomy, nodal tissue (SAN pacemaker), cardiac cycle (stroke volume 70 mL, cardiac output = SV x HR), electrocardiogram (ECG P, QRS, T waves), and double circulation.",
            "notesOverview": "The human cardiovascular system operates a high-efficiency four-chambered double circulatory loop driven by an intrinsic autorhythmic myogenic cardiac conduction system.",
            "notesSections": [
                {
                    "heading": "Cardiac Cycle Dynamics and Electrocardiography",
                    "paragraphs": [
                        "Nodal Tissue: Sinoatrial Node (SAN) in right atrium generates action potentials at 70-75/min (pacemaker), conducting to AVN, Bundle of His, and Purkinje fibres.",
                        "Cardiac Cycle (0.8 s duration): Joint diastole (0.4 s) -> Atrial systole (0.1 s, pumps 30% blood into ventricles) -> Ventricular systole (0.3 s, closes AV valves causing first heart sound 'LUB', opens semilunar valves). Ventricular diastole closes semilunar valves causing second heart sound 'DUB'.",
                        "Cardiac Output: CO = Stroke Volume (SV = 70 mL) x Heart Rate (HR = 72 bpm) approx 5000 mL/min (5 Litres/min).",
                        "Standard ECG: P-wave (atrial depolarization); QRS complex (ventricular depolarization, marks start of ventricular systole); T-wave (ventricular repolarization). Counting QRS complexes gives the heart rate.",
                        "Blood Groups: ABO system based on RBC surface antigens A and B. O group is universal donor (lacks A and B antigens); AB group is universal recipient (lacks anti-A and anti-B antibodies). Rh incompatibility in Rh- mother carrying Rh+ fetus causes erythroblastosis fetalis."
                    ],
                    "keyTakeaways": [
                        "A human heart is myogenic because its rhythmic contraction is initiated intrinsically by autoexcitable nodal muscle fibres without neural triggers.",
                        "Hepatic portal system carries blood from the intestine to the liver before returning to systemic circulation."
                    ],
                    "examTips": ["The number of QRS complexes in a given time interval equals the patient's heart rate. Elevation of ST segment is a clinical hallmark of myocardial infarction."]
                }
            ],
            "misconceptions": ["Believing 'LUB' sound is caused by blood splashing. 'LUB' is caused by the sudden acoustic closure of tricuspid and bicuspid (AV) valves at the onset of ventricular systole."],
            "formulas": [
                {
                    "label": "Cardiac Output Formula",
                    "formula": "\\text{Cardiac Output} = \\text{Stroke Volume} \\times \\text{Heart Rate} = 70 \\text{ mL} \\times 72 \\text{ bpm} \\approx 5040 \\text{ mL/min}",
                    "description": "Total volume of blood pumped by each ventricle per minute.",
                    "variables": [
                        { "symbol": "\\text{CO}", "meaning": "Cardiac Output", "unit": "mL/min" },
                        { "symbol": "\\text{SV}", "meaning": "Stroke Volume", "unit": "mL" },
                        { "symbol": "\\text{HR}", "meaning": "Heart Rate", "unit": "bpm" }
                    ]
                }
            ]
        }
    ],

    # BIO-11-16: Excretory Products and their Elimination
    "BIO-11-16": [
        {
            "title": "Nephron Physiology, Counter-Current Mechanism & Renin-Angiotensin",
            "desc": "Ammonotelism, ureotelism, uricotelism, kidney macrostructure, nephron histology (Bowman's capsule, glomerulus, PCT, loop of Henle, DCT, collecting duct), urine formation (ultrafiltration, reabsorption, secretion), GFR = 125 mL/min, counter-current multiplier, and RAAS hormonal regulation.",
            "notesOverview": "Mammalian kidneys regulate osmolality and eliminate nitrogenous metabolic wastes. The nephron couples high-pressure capillary ultrafiltration with medullary counter-current hyperosmotic gradient generation.",
            "notesSections": [
                {
                    "heading": "Urine Formation and Counter-Current Gradient",
                    "paragraphs": [
                        "Glomerular Filtration: Glomerular capillary blood pressure filters blood across 3 layers (capillary endothelium, basement membrane, podocyte filtration slits). Glomerular Filtration Rate (GFR) = 125 mL/min = 180 Litres/day. Over 99% of filtrate is reabsorbed (daily urine output = 1.5 L).",
                        "PCT: Reabsorbs 70-80% of electrolytes and water, and 100% of glucose and amino acids by active transport. Simple cuboidal brush-border epithelium.",
                        "Counter-Current Mechanism: Maintained between Loop of Henle and Vasa Recta. Descending limb of loop of Henle is permeable to water but impermeable to electrolytes (filtrate hypertonic down to 1200 mOsmol/L at hairpin bend). Ascending limb is impermeable to water and actively transports NaCl out into medullary interstitium.",
                        "Regulation of Kidney Function: Low blood volume stimulates Juxtaglomerular (JG) cells to release Renin -> converts angiotensinogen to Angiotensin I -> ACE converts to Angiotensin II (potent vasoconstrictor, stimulates adrenal cortex to release Aldosterone, causing Na+ and water reabsorption in DCT). Atrial Natriuretic Factor (ANF) released by atria opposes RAAS via vasodilation."
                    ],
                    "keyTakeaways": [
                        "Juxtamedullary nephrons have long loops of Henle dipping deep into the renal medulla, responsible for producing concentrated hypertonic urine.",
                        "Diabetes insipidus is caused by deficiency of Antidiuretic Hormone (ADH / Vasopressin), leading to excessive watery urination (polyuria)."
                    ],
                    "examTips": ["Counter-current mechanism operates between two parallel hairpin loops: the Loop of Henle and the capillary Vasa Recta!"]
                }
            ],
            "misconceptions": ["Assuming descending limb of Henle transports salt. The descending limb is strictly permeable to water only; salt is actively pumped out by the ascending limb."],
            "formulas": [
                {
                    "label": "Glomerular Filtration Rate (GFR)",
                    "formula": "\\text{GFR} = 125 \\text{ mL/min} = 180 \\text{ L/day}, \\quad \\text{Net Filtration Pressure} = P_G - (P_B + \\Pi_G) \\approx 10 \\text{ mmHg}",
                    "description": "Daily glomerular filtration volume and hydrostatic net filtration pressure across the glomerular membrane.",
                    "variables": [
                        { "symbol": "\\text{GFR}", "meaning": "Glomerular Filtration Rate", "unit": "mL/min" },
                        { "symbol": "P_G", "meaning": "Glomerular Hydrostatic Pressure", "unit": "mmHg" }
                    ]
                }
            ]
        }
    ],

    # BIO-11-17: Locomotion and Movement
    "BIO-11-17": [
        {
            "title": "Sarcomere, Sliding Filament Theory & Skeletal Framework",
            "desc": "Striated muscle histology, sarcomere structure (A-band, I-band, H-zone, Z-line), contractile proteins (myosin cross-bridges, actin, tropomyosin, troponin), sliding filament theory of muscle contraction, role of Ca2+ from sarcoplasmic reticulum, and human skeleton framework (axial and appendicular).",
            "notesOverview": "Muscle contraction operates via ATP-driven cyclic cross-bridge interactions where thin actin filaments slide over thick myosin filaments, shortening sarcomeres.",
            "notesSections": [
                {
                    "heading": "Sliding Filament Mechanism and Cross-Bridge Cycle",
                    "paragraphs": [
                        "Sarcomere: Functional unit of contraction between two successive Z-lines. A-band (anisotropic, dark, thick myosin filaments, constant length); I-band (isotropic, light, thin actin filaments, shortens during contraction); H-zone (central myosin zone not overlapped by actin, vanishes during full contraction).",
                        "Contractile Proteins: Actin filaments possess two F-actin helices with tropomyosin wound along them. Troponin complex masks myosin-binding sites on actin in resting state.",
                        "Excitation-Contraction Coupling: Action potential at neuromuscular junction causes release of acetylcholine -> depolarizes sarcolemma -> releases Ca2+ from sarcoplasmic reticulum -> Ca2+ binds Troponin C -> unmasks active sites on actin.",
                        "Cross-Bridge Cycle: Myosin head hydrolyzes ATP -> binds actin forming cross-bridge -> power stroke pulls actin toward center of sarcomere -> new ATP binds myosin head, detaching cross-bridge.",
                        "Skeletal System: 206 bones. Axial skeleton (80 bones: skull 22, vertebral column 26, ribs 12 pairs, sternum 1). Appendicular skeleton (126 bones: pectoral girdle 4, pelvic girdle 2, upper limbs 60, lower limbs 60)."
                    ],
                    "keyTakeaways": [
                        "During contraction: Sarcomere shortens, I-band shortens, H-zone narrows/disappears, but the A-band length remains STRICTLY UNCHANGED.",
                        "Rigor mortis occurs after death because ATP depletion prevents detachment of myosin cross-bridges from actin."
                    ],
                    "examTips": ["First 7 pairs of ribs are true ribs (vertebrosternal, attached directly to sternum); 8th, 9th, 10th are false ribs (vertebrochondral); 11th and 12th are floating ribs (vertebral, unattached anteriorly)."]
                }
            ],
            "misconceptions": ["Believing myosin filaments shorten during muscle contraction. Filaments do NOT change length; actin filaments slide over myosin filaments."],
            "formulas": [
                {
                    "label": "Sarcomere Contraction Band Length Dynamics",
                    "formula": "\\Delta(\\text{Sarcomere}) < 0, \\quad \\Delta(\\text{I-Band}) < 0, \\quad \\Delta(\\text{H-Zone}) \\to 0, \\quad \\Delta(\\text{A-Band}) \\equiv 0",
                    "description": "Band dimensional changes during physiological sarcomere contraction.",
                    "variables": [
                        { "symbol": "\\text{A-Band}", "meaning": "Thick Myosin Band Length", "unit": "-" }
                    ]
                }
            ]
        }
    ],

    # BIO-11-18: Neural Control and Coordination
    "BIO-11-18": [
        {
            "title": "Action Potential Conduction, Synapse & Human Brain Architecture",
            "desc": "Neuron structure (dendrites, axon, myelin sheath, nodes of Ranvier), generation and conduction of nerve impulse (resting membrane potential -70 mV, Na+/K+ ATPase pump, depolarization via Na+ influx, repolarization via K+ efflux), electrical vs chemical synapses (neurotransmitters), human brain parts (forebrain, midbrain, hindbrain), and reflex arc.",
            "notesOverview": "Neurons conduct electro-chemical impulses via voltage-gated ion channels across excitable membranes, transmitting signals across synaptic clefts using neurotransmitters.",
            "notesSections": [
                {
                    "heading": "Electrochemical Impulses and Central Nervous System",
                    "paragraphs": [
                        "Resting Membrane Potential (-70 mV): Axon interior is negative relative to exterior. Maintained by Na+/K+ ATPase pump (actively pumps 3 Na+ OUT for every 2 K+ IN, consuming 1 ATP) and high resting membrane permeability to K+ compared to Na+.",
                        "Action Potential Generation: Threshold stimulus opens voltage-gated Na+ channels -> rapid Na+ influx causes depolarization (+30 mV spike). Na+ channels inactivate; voltage-gated K+ channels open -> K+ efflux repolarizes membrane back to resting potential.",
                        "Synaptic Transmission: Action potential reaching axon terminal triggers Ca2+ influx -> synaptic vesicles fuse with presynaptic membrane -> release neurotransmitter (e.g. Acetylcholine) into synaptic cleft -> binds receptors on postsynaptic membrane opening ligand-gated ion channels.",
                        "Human Brain: Forebrain (Cerebrum: two cerebral hemispheres connected by corpus callosum, sensory/motor/association areas; Thalamus: sensory relay station; Hypothalamus: thermoregulation, hunger, thirst, endocrine control via pituitary). Midbrain (Corpora quadrigemina). Hindbrain (Pons, Cerebellum: posture and muscular coordination; Medulla oblongata: cardiovascular, respiration, swallowing centers)."
                    ],
                    "keyTakeaways": [
                        "Saltatory conduction in myelinated nerve fibres jumps from one Node of Ranvier to the next, increasing conduction speed up to 50 times faster than unmyelinated axons.",
                        "Corpus callosum is a distinctive tract of nerve fibres connecting the left and right cerebral hemispheres in mammals."
                    ],
                    "examTips": ["Na+/K+ pump stoichiometry: 3 Na+ pumped OUT, 2 K+ pumped IN per ATP hydrolyzed. Memorize this 3:2 ratio!"]
                }
            ],
            "misconceptions": ["Believing action potential amplitude increases with stronger stimuli. Action potentials obey the 'All-or-None Law': stimulus intensity is encoded by firing frequency, not spike amplitude."],
            "formulas": [
                {
                    "label": "Na+/K+ ATPase Stoichiometry & Nernst Potential",
                    "formula": "3 \\text{ Na}^+_{\\text{inside}} + 2 \\text{ K}^+_{\\text{outside}} + \\text{ATP} \\longrightarrow 3 \\text{ Na}^+_{\\text{outside}} + 2 \\text{ K}^+_{\\text{inside}} + \\text{ADP} + \\text{P}_i, \\quad V_m \\approx -70 \\text{ mV}",
                    "description": "Active electrogenic transport maintaining polarized resting axonal membrane potential.",
                    "variables": [
                        { "symbol": "V_m", "meaning": "Resting Membrane Potential", "unit": "mV" }
                    ]
                }
            ]
        }
    ],

    # BIO-11-19: Chemical Coordination and Integration
    "BIO-11-19": [
        {
            "title": "Endocrine Glands, Hormones & Mechanism of Action",
            "desc": "Endocrine glands (hypothalamus, pituitary, pineal, thyroid, parathyroid, thymus, adrenal, pancreas, gonads), peptide vs steroid hormones, hormone feedback loops, second messenger mechanism (cAMP, IP3, Ca2+), and intracellular nuclear receptor gene transcription.",
            "notesOverview": "The endocrine system coordinates long-term physiological homeostasis via blood-borne chemical messengers (hormones). Hormones act either via cell-surface second messengers or intracellular nuclear receptors.",
            "notesSections": [
                {
                    "heading": "Endocrine Organs and Hormone Signaling Pathways",
                    "paragraphs": [
                        "Pituitary Gland: Adenohypophysis secretes GH, PRL, TSH, ACTH, LH, FSH. Neurohypophysis stores and releases Oxytocin (milk ejection, uterine labor contraction) and Vasopressin / ADH (water reabsorption in kidney) produced by hypothalamus.",
                        "Thyroid Gland: Secretes T3, T4 (regulates basal metabolic rate, BMR; iodine deficiency causes simple goitre), and Thyrocalcitonin (TCT: hypocalcemic, lowers blood Ca2+).",
                        "Parathyroid Gland: Parathyroid Hormone (PTH) is hypercalcemic (increases blood Ca2+ by bone resorption and renal reabsorption). PTH and TCT act antagonistically to regulate calcium balance.",
                        "Adrenal Gland: Cortex (Mineralocorticoids: Aldosterone; Glucocorticoids: Cortisol). Medulla secretes emergency catecholamines: Adrenaline / Epinephrine and Noradrenaline ('fight or flight' hormones, increase heart rate, glycogenolysis).",
                        "Endocrine Pancreas: Islets of Langerhans. Alpha cells secrete Glucagon (hyperglycemic); Beta cells secrete Insulin (hypoglycemic, promotes glucose cellular uptake). Deficiency of insulin causes Diabetes mellitus.",
                        "Mechanism of Hormone Action: Protein/Peptide hormones (Insulin, Epinephrine, TSH) are water-soluble and cannot cross lipid membrane: bind cell-surface receptor -> activate G-protein -> generate second messenger (cAMP, IP3, Ca2+) -> biochemical cascade. Lipid-soluble steroid hormones (Estrogen, Testosterone, Cortisol) and thyroid hormones cross membrane -> bind intracellular nuclear receptors -> regulate gene expression."
                    ],
                    "keyTakeaways": [
                        "Melatonin secreted by pineal gland regulates the 24-hour diurnal rhythm (sleep-wake cycle) and body temperature.",
                        "Thymus gland secretes thymosins promoting differentiation of T-lymphocytes (cell-mediated immunity); degenerates with age, declining immunity in old people."
                    ],
                    "examTips": ["Know the antagonistic hormone pairs: Insulin (lowers blood glucose) vs Glucagon (raises blood glucose); Calcitonin (lowers blood Ca2+) vs PTH (raises blood Ca2+)."]
                }
            ],
            "misconceptions": ["Assuming steroid hormones use cAMP second messengers. Steroid hormones are lipophilic: they cross cell membranes directly and bind intracellular receptors to alter DNA transcription."],
            "formulas": [
                {
                    "label": "Calcium Homeostasis Equilibrium",
                    "formula": "\\text{Bone Resorption} \\xleftarrow{\\text{PTH (Hypercalcemic)}} [\\text{Ca}^{2+}]_{\\text{plasma}} \\xrightarrow{\\text{Calcitonin (Hypocalcemic)}} \\text{Bone Deposition}",
                    "description": "Antagonistic endocrine feedback loop regulating extracellular plasma calcium ion concentration.",
                    "variables": [
                        { "symbol": "[\\text{Ca}^{2+}]", "meaning": "Plasma Calcium Concentration", "unit": "mg/dL" }
                    ]
                }
            ]
        }
    ],

    # ==========================================
    # CLASS 12 BIOLOGY (13 Chapters)
    # ==========================================

    # BIO-12-01: Sexual Reproduction in Flowering Plants
    "BIO-12-01": [
        {
            "title": "Microsporogenesis, Megasporogenesis & Double Fertilization",
            "desc": "Flower structure, stamen and anther wall layers (epidermis, endothecium, middle layers, tapetum), microsporogenesis and pollen grain (exine of sporopollenin), megasporogenesis and 7-celled 8-nucleate embryo sac, outbreeding devices, double fertilization (syngamy + triple fusion), and endosperm development.",
            "notesOverview": "Angiosperms exhibit unique double fertilization. One sperm cell fuses with the egg cell to form the diploid zygote, while the second fuses with the central diploid polar nuclei to form the triploid nutritive endosperm.",
            "notesSections": [
                {
                    "heading": "Gametophyte Development and Double Fertilization",
                    "paragraphs": [
                        "Anther Wall: Tapetum is the innermost nutritive layer nourishing developing microspores; tapetal cells are multinucleated and polyploid.",
                        "Pollen Grain: Two-layered wall. Outer exine is made of sporopollenin (one of the most resistant organic substances known, unaffected by strong acids, bases, or high temperature, with germ pores lacking sporopollenin); inner intine is cellulose and pectin.",
                        "Female Gametophyte (Embryo Sac): Monosporic development from single functional megaspore (chalazal). 7-celled and 8-nucleate at maturity: 3 antipodals at chalazal end, 1 central cell with 2 polar nuclei, and egg apparatus (1 egg cell + 2 synergids with filiform apparatus guiding pollen tube) at micropylar end.",
                        "Double Fertilization: (1) Syngamy: Sperm (n) + Egg (n) -> Zygote (2n), developing into embryo; (2) Triple Fusion: Sperm (n) + 2 Polar Nuclei (2n) -> Primary Endosperm Nucleus (PEN, 3n), developing into nutritive endosperm.",
                        "Outbreeding Devices: Self-incompatibility, dichogamy (protandry/protogyny), unisexual flowers to prevent self-pollination and inbreeding depression."
                    ],
                    "keyTakeaways": [
                        "Double fertilization is unique to Angiosperms and completely absent in Gymnosperms.",
                        "Tender coconut water is free-nuclear endosperm (thousands of free nuclei); surrounding white coconut meat is cellular endosperm."
                    ],
                    "examTips": ["Apomixis is a form of asexual reproduction that mimics sexual reproduction by producing seeds without fertilization (e.g. Asteraceae and grasses)."]
                }
            ],
            "misconceptions": ["Believing gymnosperms have triploid endosperm. Gymnosperm endosperm is haploid (n) formed before fertilization; angiosperm endosperm is triploid (3n) formed after triple fusion."],
            "formulas": [
                {
                    "label": "Double Fertilization Stoichiometry",
                    "formula": "\\text{Syngamy: } n + n \\longrightarrow 2n \\; (\\text{Zygote}), \\quad \\text{Triple Fusion: } n + 2n \\longrightarrow 3n \\; (\\text{PEN / Endosperm})",
                    "description": "Ploidy mechanics of dual angiosperm fertilization events.",
                    "variables": [
                        { "symbol": "n", "meaning": "Gametic Haploid Genome", "unit": "-" }
                    ]
                }
            ]
        }
    ],

    # BIO-12-02: Human Reproduction
    "BIO-12-02": [
        {
            "title": "Spermatogenesis, Oogenesis, Menstrual Cycle & Embryogenesis",
            "desc": "Male reproductive system (testes, Leydig cells, Sertoli cells), female reproductive system (ovaries, fallopian tubes, uterus), spermatogenesis vs oogenesis, hormonal control of menstrual cycle (LH surge, follicular and luteal phases), fertilization in ampulla, cleavage, blastocyst implantation, and placenta hormones.",
            "notesOverview": "Human reproduction involves gametogenesis, hormonal cyclicity, internal fertilization in the fallopian tube ampulla, blastocyst implantation, and placental endocrine coordination.",
            "notesSections": [
                {
                    "heading": "Gametogenesis and the Menstrual Cycle",
                    "paragraphs": [
                        "Spermatogenesis: In seminiferous tubules. Spermatogonia (2n) -> Primary spermatocytes (2n, undergo meiosis I) -> Secondary spermatocytes (n, meiosis II) -> Spermatids (n) -> mature Spermatozoa (spermiogenesis). Sertoli cells nourish germ cells; Leydig cells secrete testosterone under LH stimulation.",
                        "Oogenesis: Initiated during embryonic development. Primary oocytes arrest in prophase I until puberty. Meiosis I completes prior to ovulation producing secondary oocyte (n) and 1st polar body. Meiosis II completes ONLY upon fertilization by sperm, producing ovum and 2nd polar body.",
                        "Menstrual Cycle (28 days): Menstrual phase (days 1-5, sloughing of endometrium) -> Follicular / Proliferative phase (days 6-13, FSH stimulates follicle development, estrogen regenerates endometrium) -> Ovulatory phase (day 14, rapid LH surge induces rupture of Graafian follicle and release of secondary oocyte) -> Luteal / Secretory phase (days 15-28, ruptured follicle transforms into Corpus Luteum secretes high progesterone maintaining endometrium).",
                        "Fertilization & Implantation: Occurs at ampullary-isthmic junction of fallopian tube. Sperm acrosome enzymes penetrate corona radiata and zona pellucida (inducing cortical reaction to block polyspermy). Cleavage forms morula -> blastocyst. Outer trophoblast implants into uterine endometrium; inner cell mass gives rise to embryo.",
                        "Placental Hormones: Human Chorionic Gonadotropin (hCG), Human Placental Lactogen (hPL), Estrogen, Progesterone, and Relaxin (secreted by ovary during late pregnancy). hCG and hPL are produced exclusively during pregnancy."
                    ],
                    "keyTakeaways": [
                        "Corpus luteum degenerates into Corpus albicans if fertilization does not occur, causing progesterone withdrawal and menstrual bleeding.",
                        "Detection of hCG in urine is the basis of all standard home pregnancy test kits."
                    ],
                    "examTips": ["The LH surge on day 14 of a 28-day menstrual cycle is the direct physiological trigger for ovulation!"]
                }
            ],
            "misconceptions": ["Assuming oogenesis finishes before birth. Oogenesis completes meiosis II ONLY after a sperm physically penetrates the secondary oocyte."],
            "formulas": [
                {
                    "label": "Spermatogenesis vs Oogenesis Yield Ratio",
                    "formula": "1 \\text{ Primary Spermatocyte (2n)} \\longrightarrow 4 \\text{ Functional Sperm (n)}, \\quad 1 \\text{ Primary Oocyte (2n)} \\longrightarrow 1 \\text{ Ovum (n)} + 2\\text{-}3 \\text{ Polar Bodies}",
                    "description": "Yield ratio of viable gametes per primary meiotic precursor cell.",
                    "variables": [
                        { "symbol": "n", "meaning": "Haploid Gamete", "unit": "-" }
                    ]
                }
            ]
        }
    ],

    # BIO-12-03: Reproductive Health
    "BIO-12-03": [
        {
            "title": "Contraceptive Methods, MTP & Assisted Reproductive Technologies",
            "desc": "Need for reproductive health, STIs, contraceptive methods (natural, barrier, IUDs copper-releasing and hormone-releasing, oral pills Saheli, surgical tubectomy/vasectomy), Medical Termination of Pregnancy (MTP Act), amniocentesis misuse, and ART (IVF-ET, ZIFT, GIFT, ICSI).",
            "notesOverview": "Reproductive health addresses family planning, sexually transmitted infections, and infertility treatment via Assisted Reproductive Technologies (ART).",
            "notesSections": [
                {
                    "heading": "Contraceptive Classification and Infertility Interventions",
                    "paragraphs": [
                        "Barrier Methods: Condoms protect against both pregnancy and sexually transmitted infections (STIs/STDs including AIDS, Hepatitis B, Syphilis).",
                        "Intrauterine Devices (IUDs): Non-medicated (Lippes loop); Copper-releasing (CuT, Cu7, Multiload 375: Cu ions suppress sperm motility and fertilizing capacity); Hormone-releasing (Progestasert, LNG-20: make uterus unsuitable for implantation and cervix hostile to sperms).",
                        "Oral Pills: 'Saheli' developed by CDRI Lucknow: once-a-week, non-steroidal pill with very few side effects and high contraceptive value.",
                        "Surgical Methods: Irreversible terminal methods. Vasectomy in males (cutting and tying of vas deferens); Tubectomy in females (cutting and tying of fallopian tubes).",
                        "ART Techniques: In Vitro Fertilization (IVF, 'test-tube baby'); ZIFT (Zygote Intra-Fallopian Transfer: embryo up to 8 blastomeres transferred into fallopian tube); IUT (Intra-Uterine Transfer: embryo with > 8 blastomeres transferred into uterus); GIFT (Gamete Intra-Fallopian Transfer: ovum transferred into fallopian tube of recipient female who cannot produce one); ICSI (Intra-Cytoplasmic Sperm Injection: sperm directly injected into ovum)."
                    ],
                    "keyTakeaways": [
                        "Amniocentesis is a fetal sex determination and chromosomal diagnostic test analyzing amniotic fluid; statutory ban imposed in India to curb female foeticide.",
                        "Hepatitis B, Genital Herpes, and HIV infections are non-curable STIs."
                    ],
                    "examTips": ["Distinguish ZIFT from IUT: ZIFT transfers embryos up to 8 blastomeres into fallopian tube; IUT transfers embryos with more than 8 blastomeres directly into uterus."]
                }
            ],
            "misconceptions": ["Believing MTP is safe at all gestational ages. MTP is considered relatively safe only during the first trimester (up to 12 weeks of pregnancy)."],
            "formulas": [
                {
                    "label": "Assisted Reproductive Embryo Transfer Boundary",
                    "formula": "\\text{Embryo} \\le 8 \\text{ blastomeres} \\implies \\text{ZIFT (Fallopian Tube)}, \\quad \\text{Embryo} > 8 \\text{ blastomeres} \\implies \\text{IUT (Uterine Cavity)}",
                    "description": "Clinical transfer site protocol based on cleavage blastomere count in IVF.",
                    "variables": [
                        { "symbol": "\\text{Blastomeres}", "meaning": "Cleavage Stage Cell Count", "unit": "-" }
                    ]
                }
            ]
        }
    ],

    # BIO-12-04: Principles of Inheritance and Variation
    "BIO-12-04": [
        {
            "title": "Mendelian Genetics, Linkage & Genetic Disorders",
            "desc": "Mendel’s laws of inheritance (dominance, segregation 3:1, independent assortment 9:3:3:1), incomplete dominance, codominance (ABO blood groups), Morgan’s Drosophila linkage and recombination, chromosomal theory of inheritance, sex determination (XX-XY, ZZ-ZW, honeybee haplodiploidy), and Mendelian and chromosomal disorders (Down, Turner, Klinefelter).",
            "notesOverview": "Genetics investigates heredity and variation. Mendel established particulate inheritance principles, which Morgan linked to physical chromosome loci exhibiting crossing over and sex-linked inheritance.",
            "notesSections": [
                {
                    "heading": "Mendelian Ratios and Chromosomal Non-Disjunction",
                    "paragraphs": [
                        "Law of Segregation (Monohybrid Cross): Alleles segregate during gamete formation so each gamete receives only one allele. Phenotypic ratio = 3 : 1; Genotypic ratio = 1 : 2 : 1. Test cross (dominant phenotype x homozygous recessive) gives 1 : 1 ratio.",
                        "Law of Independent Assortment (Dihybrid Cross): Dihybrid phenotypic ratio = 9 : 3 : 3 : 1. Fails when genes are closely linked on the same chromosome.",
                        "Linkage (T.H. Morgan): Physical association of genes on the same chromosome. Recombination frequency between linked genes is proportional to the distance between them (Alfred Sturtevant constructed first genetic linkage maps where 1% recombination = 1 map unit / centimorgan).",
                        "Sex Determination in Honeybees: Haplodiploid system. Males (drones) develop parthenogenetically from unfertilized eggs (haploid, n=16); females develop from fertilized eggs (diploid, 2n=32).",
                        "Mendelian Disorders: Haemophilia (X-linked recessive, defect in blood clotting cascade); Sickle-cell anaemia (autosomal recessive point mutation in beta-globin gene, GAG -> GUG substituting glutamic acid with valine at position 6); Phenylketonuria (autosomal recessive metabolic defect in phenylalanine hydroxylase).",
                        "Chromosomal Disorders: Down’s syndrome (Trisomy 21, 2n+1 = 47); Klinefelter’s syndrome (XXY male with gynaecomastia, 47,XXY); Turner’s syndrome (monosomy X female, sterile with webbed neck, 45,X0)."
                    ],
                    "keyTakeaways": [
                        "Sickle-cell trait heterozygotes (HbA HbS) have selective survival advantage against falciparum malaria in endemic zones.",
                        "Down’s syndrome is caused by non-disjunction of chromosome 21 during maternal meiotic oogenesis."
                    ],
                    "examTips": ["Sickle cell anemia point mutation substitution: 6th codon GAG (coding for Glutamic acid) mutates to GUG (coding for Valine)!"]
                }
            ],
            "misconceptions": ["Assuming independent assortment holds for all gene pairs. Independent assortment applies ONLY to genes located on different chromosomes or very far apart on the same chromosome."],
            "formulas": [
                {
                    "label": "Mendelian Phenotypic Ratios & Recombination Frequency",
                    "formula": "\\text{Monohybrid: } 3:1, \\quad \\text{Dihybrid: } 9:3:3:1, \\quad \\text{Recombination Frequency} = \\frac{\\text{Recombinant Progeny}}{\\text{Total Progeny}} \\times 100",
                    "description": "Classical inheritance ratios and Morgan-Sturtevant centimorgan genetic mapping formula.",
                    "variables": [
                        { "symbol": "\\text{RF}", "meaning": "Recombination Frequency", "unit": "\\% \\text{ or cM}" }
                    ]
                }
            ]
        }
    ],

    # BIO-12-05: Molecular Basis of Inheritance
    "BIO-12-05": [
        {
            "title": "DNA Double Helix, Replication, Transcription & Translation",
            "desc": "Watson-Crick B-DNA double helix model, Chargaff's rules, nucleosome packaging, Avery-MacLeod-McCarty & Hershey-Chase (32P/35S) experiments proving DNA as genetic material, Meselson-Stahl semi-conservative replication, transcription unit, post-transcriptional splicing/capping/tailing, genetic code features, tRNA cloverleaf, and Jacob-Monod Lac Operon.",
            "notesOverview": "Molecular biology elucidates genetic transmission through the Central Dogma: DNA -> RNA -> Protein. Replication is semi-conservative, transcription produces messenger RNA, and ribosomal translation synthesizes polypeptide chains according to the universal triplet genetic code.",
            "notesSections": [
                {
                    "heading": "Central Dogma and the Lac Operon",
                    "paragraphs": [
                        "B-DNA Structure: Antiparallel double helix, pitch = 3.4 nm with 10 base pairs per turn (0.34 nm distance between base pairs). Chargaff's Rule: [A] = [T] and [G] = [C], so [A + G] / [T + C] = 1.",
                        "Hershey-Chase Experiment (1952): Used bacteriophage T2 labeled with 35S (capsid protein) and 32P (DNA core). Radioactive 32P entered E. coli cells, proving definitively that DNA is the genetic material.",
                        "Meselson-Stahl Experiment (1958): Proved semi-conservative replication using 15N heavy isotope and CsCl density gradient centrifugation.",
                        "Genetic Code: Triplet, degenerate (61 codons code for 20 amino acids), unambiguous, non-overlapping, and nearly universal. AUG is dual functional (codes for Methionine and acts as initiator codon). Stop codons: UAA (ochre), UAG (amber), UGA (opal).",
                        "Transcription: DNA-dependent RNA polymerase synthesizes RNA in 5' -> 3' direction. Eukaryotic pre-mRNA undergoes: (1) Splicing (introns removed by spliceosome); (2) 5' Capping (methylguanosine triphosphate added); (3) 3' Tailing (polyadenylation with 200-300 adenylate residues).",
                        "Lac Operon: Inducible operon. Regulator gene i produces repressor protein that binds operator (o) in absence of lactose. When inducer (allolactose/lactose) binds repressor, repressor inactivates, allowing RNA polymerase to transcribe structural genes: lac z (beta-galactosidase), lac y (permease), and lac a (transacetylase)."
                    ],
                    "keyTakeaways": [
                        "tRNA is an adapter molecule: cloverleaf 2D secondary structure, inverted L-shaped 3D tertiary structure.",
                        "DNA ligase joins Okazaki fragments on the lagging strand during replication."
                    ],
                    "examTips": ["The genetic code is DEGENERATE: some amino acids are coded by more than one codon (e.g. Leucine has 6 codons)."]
                }
            ],
            "misconceptions": ["Assuming RNA polymerase requires primers for transcription. DNA polymerase requires a primer, but RNA polymerase initiates RNA synthesis de novo without primers."],
            "formulas": [
                {
                    "label": "Chargaff’s Base-Pairing Rules",
                    "formula": "[A] = [T], \\quad [G] = [C], \\quad \\frac{[A] + [G]}{[T] + [C]} = 1.0, \\quad \\%A + \\%T + \\%G + \\%C = 100\\%",
                    "description": "Stoichiometric base-equivalence rules in double-stranded DNA.",
                    "variables": [
                        { "symbol": "[A], [T]", "meaning": "Adenine and Thymine Molar Concentrations", "unit": "-" },
                        { "symbol": "[G], [C]", "meaning": "Guanine and Cytosine Molar Concentrations", "unit": "-" }
                    ]
                }
            ]
        }
    ],

    # BIO-12-06: Evolution
    "BIO-12-06": [
        {
            "title": "Origin of Life, Natural Selection & Hardy-Weinberg Principle",
            "desc": "Miller-Urey experiment (methane, ammonia, hydrogen, water vapor producing amino acids), homologous vs analogous organs (divergent vs convergent evolution), adaptive radiation (Darwin's finches), natural selection (industrial melanism), Hardy-Weinberg equilibrium p^2 + 2pq + q^2 = 1, and human evolutionary lineage (Dryopithecus to Homo sapiens).",
            "notesOverview": "Evolutionary biology investigates the origin of life and species diversification. Natural selection acts on phenotypic variations, altering population allele frequencies over geological timescales.",
            "notesSections": [
                {
                    "heading": "Evolutionary Evidence and Population Genetics",
                    "paragraphs": [
                        "Miller-Urey Experiment (1953): Simulated primitive Earth atmosphere (CH4, NH3, H2, H2O at 800 °C with electric spark discharge) producing glycine, alanine, and aspartic acid, validating Oparin-Haldane chemical evolution.",
                        "Homologous Organs (Divergent Evolution): Same anatomical origin, different functions (e.g. forelimbs of cheetah, whale, bat, human; thorns of Bougainvillea and tendrils of Cucurbita). Indicates common ancestry.",
                        "Analogous Organs (Convergent Evolution): Different origin, similar functions due to similar environmental selective pressures (e.g. wings of butterfly and bird; eye of octopus and mammal; sweet potato root and potato stem).",
                        "Adaptive Radiation: Diversification of an ancestral species into different ecological niches (e.g. Darwin's finches in Galapagos Islands, Australian marsupials).",
                        "Hardy-Weinberg Principle: Allele frequencies in a large, randomly mating population remain constant from generation to generation in the absence of evolutionary influences (mutation, gene flow, genetic drift, natural selection, non-random mating): p^2 + 2pq + q^2 = 1, where p + q = 1."
                    ],
                    "keyTakeaways": [
                        "Genetic Drift (Sewall Wright Effect): Random fluctuations in allele frequencies occurring purely by chance in SMALL populations (Founder effect, Bottleneck effect).",
                        "Human Evolution Chronology: Dryopithecus -> Ramapithecus -> Australopithecus (used stone weapons, ate fruit) -> Homo habilis (first human-like, cranial capacity 650-800 cc) -> Homo erectus (1891 Java man, 900 cc, ate meat) -> Neanderthal man (1400 cc, buried dead) -> Homo sapiens."
                    ],
                    "examTips": ["In Hardy-Weinberg calculations: p = frequency of dominant allele A; q = frequency of recessive allele a; p^2 = AA; 2pq = Aa (heterozygotes); q^2 = aa (recessive trait)."]
                }
            ],
            "misconceptions": ["Assuming evolutionary changes occur within an individual's lifetime. Evolution is a population-level phenomenon measured by changes in allele frequencies across generations."],
            "formulas": [
                {
                    "label": "Hardy-Weinberg Population Equilibrium",
                    "formula": "p + q = 1, \\quad p^2 + 2pq + q^2 = 1.0",
                    "description": "Binomial expansion describing stable genotype frequencies in panmictic populations.",
                    "variables": [
                        { "symbol": "p", "meaning": "Frequency of Dominant Allele", "unit": "-" },
                        { "symbol": "q", "meaning": "Frequency of Recessive Allele", "unit": "-" },
                        { "symbol": "2pq", "meaning": "Heterozygous Genotype Frequency", "unit": "-" }
                    ]
                }
            ]
        }
    ],

    # BIO-12-07: Human Health and Disease
    "BIO-12-07": [
        {
            "title": "Pathogens, Innate/Acquired Immunity, AIDS & Cancer",
            "desc": "Infectious diseases (Typhoid Widal test, Malaria Plasmodium life cycle in mosquito and human, Pneumonia, Amoebiasis, Ringworm), Innate immunity barriers, Acquired immunity (B-cells antibodies IgG/IgA/IgM, T-cells cell-mediated, active vs passive immunity, colostrum IgA), AIDS (HIV retrovirus life cycle, ELISA diagnostic), and Cancer (oncogenes, contact inhibition loss, metastasis).",
            "notesOverview": "Human immunology explores defense barriers against pathogens. Autoimmunity, immunodeficiency (AIDS), and malignant cellular transformations (cancer) represent key immunological dysfunctions.",
            "notesSections": [
                {
                    "heading": "Immunology, Pathogenic Life Cycles, and Oncology",
                    "paragraphs": [
                        "Malaria Life Cycle: Plasmodium vivax. Female Anopheles mosquito injects sporozoites into human -> reproduce asexually in liver cells -> rupture RBCs releasing toxic haemozoin (responsible for recurring chills and high fever every 3-4 days) -> sexual stages (gametocytes) taken up by mosquito -> fertilization occurs in mosquito gut -> sporozoites migrate to salivary glands.",
                        "Innate Immunity Barriers: Physical (skin, mucus); Physiological (stomach HCl, saliva lysozyme); Cellular (neutrophils, macrophages, NK cells); Cytokine (interferons protect uninfected cells from viral invasion).",
                        "Acquired Immunity: Humoral (B-lymphocytes produce antibodies H2L2: IgG most abundant, IgA in colostrum breast milk, IgE in allergies); Cell-Mediated Immunity (T-lymphocytes responsible for graft rejection in organ transplants).",
                        "AIDS: Caused by HIV (Retrovirus with RNA genome and reverse transcriptase). Infects macrophages ('HIV factory') and helper T-lymphocytes (CD4+ T-cells). Progressive depletion of helper T-cells leads to opportunistic infections (Mycobacterium, Toxoplasma). Diagnosed by ELISA; confirmed by Western blot.",
                        "Cancer: Normal cells exhibit contact inhibition; cancer cells lose contact inhibition forming tumors (benign vs malignant). Malignant tumors exhibit metastasis (cancer cells enter bloodstream and form secondary tumors at distant sites, the most dreaded property of cancer). Caused by oncogenic viruses and carcinogens."
                    ],
                    "keyTakeaways": [
                        "Colostrum secreted during the first days of lactation contains abundant IgA antibodies providing natural passive immunity to newborns.",
                        "Cell-mediated immunity mediated by T-lymphocytes is responsible for the body's rejection of organ transplants: patients must take immunosuppressants (cyclosporin A) for life."
                    ],
                    "examTips": ["Identify antibody chain structure: each antibody molecule has two heavy chains and two light chains represented as H2L2!"]
                }
            ],
            "misconceptions": ["Believing AIDS kills patients directly. HIV destroys helper T-cells, leaving the immune system defenseless against opportunistic infections that ultimately prove fatal."],
            "formulas": [
                {
                    "label": "Antibody Stoichiometry Structure",
                    "formula": "\\text{Monomeric Antibody} = \\text{H}_2\\text{L}_2 \\quad (2 \\text{ Heavy Chains} + 2 \\text{ Light Chains linked by S-S bridges})",
                    "description": "Biochemical quaternary structure of immunoglobulin G monomer.",
                    "variables": [
                        { "symbol": "\\text{H}_2\\text{L}_2", "meaning": "Immunoglobulin Subunit Formula", "unit": "-" }
                    ]
                }
            ]
        }
    ],

    # BIO-12-08: Microbes in Human Welfare
    "BIO-12-08": [
        {
            "title": "Microbes in Household, Sewage Treatment & Biocontrol",
            "desc": "Lactic acid bacteria (LAB) in curd, Baker’s yeast (Saccharomyces cerevisiae), antibiotics (Penicillium notatum), bioactive molecules (Cyclosporin A from Trichoderma polysporum, Statins from Monascus purpureus), Sewage treatment plants (STPs: primary physical settling, secondary biological aeration tanks, BOD reduction), biogas production (methanogens), and biofertilizers (Mycorrhiza, Rhizobium).",
            "notesOverview": "Microorganisms drive vital industrial, ecological, and biotechnological processes including wastewater purification, pharmaceutical production, and organic agriculture.",
            "notesSections": [
                {
                    "heading": "Sewage Treatment and Industrial Microbial Products",
                    "paragraphs": [
                        "Household: Lactobacillus (LAB) converts milk to curd, improving nutritional quality by increasing vitamin B12; Saccharomyces cerevisiae (Brewer’s/Baker’s yeast) ferments dough releasing CO2.",
                        "Industrial Chemicals: Citric acid (Aspergillus niger fungus); Acetic acid (Acetobacter aceti bacterium); Butyric acid (Clostridium butyricum); Lactic acid (Lactobacillus).",
                        "Bioactive Molecules: Cyclosporin A (immunosuppressive agent used in organ transplant patients, produced by fungus Trichoderma polysporum); Statins (blood-cholesterol lowering agents, competitively inhibit cholesterol synthesis enzyme, produced by yeast Monascus purpureus); Streptokinase (clot buster from Streptococcus).",
                        "Sewage Treatment (STP): Primary treatment (physical removal of floating debris by filtration and grit by sedimentation). Secondary (Biological) treatment: Aerobic flocs (bacteria + fungal filaments) consume organic matter in aeration tanks, drastically reducing Biochemical Oxygen Demand (BOD). Effluent passed into anaerobic sludge digesters where methanogens produce biogas (CH4, CO2, H2S).",
                        "Biocontrol: Bacillus thuringiensis (Bt, toxic Cry proteins against caterpillar pests); Trichoderma (free-living fungus controlling root-borne plant pathogens); Baculoviruses (genus Nucleopolyhedrovirus, narrow-spectrum species-specific insecticides safe for non-target organisms)."
                    ],
                    "keyTakeaways": [
                        "BOD (Biochemical Oxygen Demand) measures organic pollution in water: higher BOD indicates greater pollution and lower dissolved oxygen.",
                        "Glomus fungus forms mycorrhizal associations with plant roots, absorbing phosphorus and providing resistance to root-borne pathogens."
                    ],
                    "examTips": ["Cyclosporin A is from Trichoderma polysporum (immunosuppressive); Statins are from Monascus purpureus (cholesterol lowering). Match these correctly in NEET!"]
                }
            ],
            "misconceptions": ["Assuming secondary sewage treatment is chemical. Secondary sewage treatment is entirely BIOLOGICAL, relying on aerobic microbial flocs followed by anaerobic methanogenic digesters."],
            "formulas": [
                {
                    "label": "Biochemical Oxygen Demand Correlation",
                    "formula": "\\text{Water Pollution Degree} \\propto \\text{BOD} \\propto \\frac{1}{\\text{Dissolved Oxygen (DO)}}",
                    "description": "Inverse relationship between biological oxygen demand and dissolved aquatic oxygen.",
                    "variables": [
                        { "symbol": "\\text{BOD}", "meaning": "Biochemical Oxygen Demand", "unit": "mg/L" }
                    ]
                }
            ]
        }
    ],

    # BIO-12-09: Biotechnology: Principles and Processes
    "BIO-12-09": [
        {
            "title": "Recombinant DNA Technology: Restriction Enzymes, Cloning Vectors & PCR",
            "desc": "Principles of genetic engineering, restriction endonucleases (molecular scissors, palindromic recognition sequences, sticky ends), DNA ligase, agarose gel electrophoresis (ethidium bromide, UV transillumination), plasmid cloning vector pBR322 (ori, rop, selectable markers ampR and tetR, insertional inactivation), competent cells, Polymerase Chain Reaction (PCR: denaturation, annealing, extension by Taq polymerase), and stirred-tank bioreactors.",
            "notesOverview": "Recombinant DNA technology manipulates genetic material in vitro. Restriction endonucleases cleave target genes at palindromic sequences for ligation into specialized plasmid vectors and exponential PCR amplification.",
            "notesSections": [
                {
                    "heading": "Tools and Protocol of Genetic Engineering",
                    "paragraphs": [
                        "Restriction Enzymes (Molecular Scissors): Discovered by Arber, Nathan, and Smith. Cleave phosphodiester backbones of both DNA strands at specific palindromic sequences (e.g. EcoRI recognizes 5'-GAATTC-3' and cuts between G and A, producing cohesive sticky ends).",
                        "Agarose Gel Electrophoresis: Negatively charged DNA fragments migrate toward the positive anode. Smaller fragments move farther (sieving effect). Visualized by staining with ethidium bromide (EtBr) under UV light as bright orange bands. Extraction of DNA band from gel is termed elution.",
                        "Cloning Vector pBR322 Features: Origin of replication (ori, controls copy number); Selectable markers (ampR and tetR genes to distinguish transformants from non-transformants); Insertional Inactivation (ligation of foreign gene into BamHI site of tetR destroys tetracycline resistance, allowing selection of recombinants via replica plating; or lac z gene with X-gal chromogenic substrate producing white recombinant colonies).",
                        "Polymerase Chain Reaction (PCR, Kary Mullis): Amplifies DNA a billion-fold in 30 cycles: (1) Denaturation (94-96 °C: strands separate); (2) Annealing (50-56 °C: oligonucleotide primers bind); (3) Extension (72 °C: thermostable Taq DNA polymerase isolated from bacterium Thermus aquaticus synthesizes complementary strands).",
                        "Downstream Processing: Separation, purification, and clinical quality testing of recombinant protein products prior to commercial marketing."
                    ],
                    "keyTakeaways": [
                        "Taq polymerase is used in PCR because it remains thermostably active at high denaturation temperatures (94 °C).",
                        "Microinjection injects recombinant DNA directly into animal cell nuclei; biolistics/gene gun shoots gold/tungsten microparticles coated with DNA into plant cells."
                    ],
                    "examTips": ["Insertional inactivation: Recombinant colonies in lac z selection appear WHITE because beta-galactosidase is inactivated; non-recombinant colonies appear BLUE with X-gal!"]
                }
            ],
            "misconceptions": ["Assuming restriction enzymes cut single-stranded DNA randomly. Restriction endonucleases recognize specific palindromic double-stranded sequences."],
            "formulas": [
                {
                    "label": "PCR Theoretical Amplification Yield",
                    "formula": "N = N_0 \\times 2^n \\quad (\\text{After } n = 30 \\text{ cycles: } 2^{30} \\approx 10^9 \\text{ copies})",
                    "description": "Exponential doubling of DNA template copies across thermal PCR cycles.",
                    "variables": [
                        { "symbol": "N_0", "meaning": "Initial DNA Copies", "unit": "-" },
                        { "symbol": "n", "meaning": "PCR Thermal Cycles Count", "unit": "-" }
                    ]
                }
            ]
        }
    ],

    # BIO-12-10: Biotechnology and its Applications
    "BIO-12-10": [
        {
            "title": "Bt Crops, RNA Interference & Recombinant Therapeutics",
            "desc": "Transgenic agricultural applications: Bt cotton (Bacillus thuringiensis, endotoxin CryIAc and CryIIAb against bollworms, activated by alkaline insect gut pH), RNA interference (RNAi, gene silencing via dsRNA in tobacco roots against Meloidogyne incognita nematode), genetically engineered human insulin (Eli Lilly, separate A and B chains linked by disulfide bonds, devoid of C-peptide), gene therapy for ADA deficiency, and transgenic animals.",
            "notesOverview": "Biotechnology addresses agricultural productivity, pharmaceutical medicine, and gene therapy by introducing recombinant genes into target host organisms.",
            "notesSections": [
                {
                    "heading": "Agricultural Biotechnology and Human Therapeutics",
                    "paragraphs": [
                        "Bt Cotton: Bacillus thuringiensis produces crystalline protein protoxins (Cry proteins). Ingested by insect -> solubilized by alkaline pH of insect midgut -> activated toxin binds midgut epithelial cells -> creates pores causing cell swelling and lysis. CryIAc and CryIIAb control cotton bollworms; CryIAb controls corn borer.",
                        "RNA Interference (RNAi): Cellular defense mechanism in all eukaryotes. Double-stranded RNA (dsRNA) triggers RNA-induced silencing complex (RISC), which binds and cleaves target complementary mRNA of pathogen (nematode Meloidogyne incognita), preventing translation (gene silencing).",
                        "Genetically Engineered Insulin (Humulin): Human pro-insulin contains an extra connecting C-peptide which is removed during maturation. Eli Lilly (1983) synthesized DNA sequences for human insulin chain A and chain B separately, cloned them into E. coli, extracted them, and combined them via disulfide bonds to produce mature active human insulin without C-peptide.",
                        "Gene Therapy: First clinical gene therapy was given in 1990 to a 4-year-old girl with Adenosine Deaminase (ADA) deficiency causing severe combined immunodeficiency (SCID). Lymphocytes from patient's blood were cultured -> functional ADA cDNA introduced using retroviral vector -> infused back into patient. Permanent cure requires gene introduction into embryonic bone marrow cells.",
                        "Transgenic Animals: Transgenic cow 'Rosie' (1997) produced human protein-enriched milk (2.4 grams per litre) containing human alpha-lactalbumin, nutritionally superior for human babies."
                    ],
                    "keyTakeaways": [
                        "Mature functional human insulin contains 51 amino acids (Chain A = 21, Chain B = 30) linked by disulfide bonds, completely lacking C-peptide.",
                        "Bt toxin does NOT kill the bacterium itself because it exists as an inactive protoxin; it activates only in the alkaline gut pH of insects."
                    ],
                    "examTips": ["ADA deficiency is an autosomal recessive genetic defect; permanent cure is possible ONLY if functional ADA gene is introduced at early embryonic stages!"]
                }
            ],
            "misconceptions": ["Believing mature insulin includes the C-peptide. The C-peptide is present only in the pro-hormone and is enzymatically excised during maturation."],
            "formulas": [
                {
                    "label": "Mature Insulin Subunit Stoichiometry",
                    "formula": "\\text{Proinsulin} \\xrightarrow{-\\text{C-Peptide}} \\text{Active Insulin} = \\text{Chain A (21 aa)} + \\text{Chain B (30 aa)} \\; (\\text{Disulfide Linked})",
                    "description": "Proteolytic maturation of human recombinant insulin.",
                    "variables": [
                        { "symbol": "\\text{aa}", "meaning": "Amino Acid Residues Count (51 Total)", "unit": "-" }
                    ]
                }
            ]
        }
    ],

    # BIO-12-11: Organisms and Populations
    "BIO-12-11": [
        {
            "title": "Population Growth Models, Adaptations & Interspecific Interactions",
            "desc": "Responses to abiotic factors (regulators, conformers, migration, diapause), physiological adaptations (Allen’s rule, altitude sickness acclimatization), population attributes (birth rate, death rate, age pyramids), exponential growth dN/dt = rN, logistic growth dN/dt = rN(1 - N/K), carrying capacity K, and interspecific interactions (mutualism, competition, predation, parasitism, commensalism, amensalism).",
            "notesOverview": "Ecology investigates organisms' relationships with physical environments and biotic communities. Population ecology mathematically models demographic growth trajectories and competitive species interactions.",
            "notesSections": [
                {
                    "heading": "Population Growth Models and Interspecific Dynamics",
                    "paragraphs": [
                        "Ecological Adaptations: Allen’s Rule (mammals in colder climates have shorter ears and limbs to minimize heat loss); High Altitude Acclimatization (body compensates for low atmospheric pO2 by increasing RBC production, increasing breathing rate, and decreasing hemoglobin-O2 binding affinity).",
                        "Exponential Growth (Unlimited Resources): J-shaped curve: dN/dt = (b - d) N = r N. Integrated form: N_t = N_0 e^(r t), where r is intrinsic rate of natural increase.",
                        "Logistic Growth (Verhulst-Pearl, Limited Resources): S-shaped sigmoid curve: dN/dt = r N [(K - N) / K], where K is environmental carrying capacity. More realistic model in nature as resources are finite.",
                        "Interspecific Interactions: Mutualism (+, +: mycorrhiza, lichens, fig-wasp coevolution); Commensalism (+, 0: orchid on mango tree, barnacles on whale, cattle egret and grazing cattle); Parasitism (+, -: Cuscuta on host, liver fluke, brood parasitism in cuckoo/koel); Predation (+, -: keeps prey populations under control, transfers energy); Competition (-, -: Gause’s Competitive Exclusion Principle states two closely related species competing for identical limiting resources cannot coexist indefinitely; MacArthur showed 5 species of warblers coexisted via resource partitioning); Amensalism (-, 0: Penicillium producing penicillin inhibiting bacterial growth)."
                    ],
                    "keyTakeaways": [
                        "Carrying capacity K represents the maximum population size that an environment's resources can sustainably support.",
                        "Brood parasitism: The koel (cuckoo) lays its eggs in the nest of a crow, evolving eggs resembling host eggs to prevent rejection."
                    ],
                    "examTips": ["Gause’s Competitive Exclusion Principle holds when resources are limiting; Resource partitioning (MacArthur's warblers) avoids competitive exclusion by foraging at different times!"]
                }
            ],
            "misconceptions": ["Assuming exponential growth can continue indefinitely in nature. Real populations invariably encounter resource limits and follow the logistic Verhulst-Pearl sigmoid curve."],
            "formulas": [
                {
                    "label": "Exponential and Logistic Population Growth",
                    "formula": "\\frac{dN}{dt} = r N \\; (\\text{Exponential: } N_t = N_0 e^{rt}), \\quad \\frac{dN}{dt} = r N \\left( \\frac{K - N}{K} \\right) \\; (\\text{Verhulst-Pearl Logistic})",
                    "description": "Differential growth equations modeling density-independent exponential vs density-dependent logistic populations.",
                    "variables": [
                        { "symbol": "N", "meaning": "Population Density", "unit": "-" },
                        { "symbol": "r", "meaning": "Intrinsic Rate of Natural Increase", "unit": "\\text{time}^{-1}" },
                        { "symbol": "K", "meaning": "Carrying Capacity", "unit": "-" }
                    ]
                }
            ]
        }
    ],

    # BIO-12-12: Ecosystem
    "BIO-12-12": [
        {
            "title": "Ecosystem Productivity, Decomposition & Energy Flow 10% Law",
            "desc": "Ecosystem structure and function, productivity (Gross Primary Productivity GPP, Net Primary Productivity NPP = GPP - R), decomposition steps (fragmentation, leaching, catabolism, humification, mineralization), Lindeman’s 10% energy transfer law, food chains and webs, and ecological pyramids of number, biomass, and energy (always upright).",
            "notesOverview": "An ecosystem is a functional ecological unit where biotic communities interact with physical environments. Energy flows unidirectionally through trophic levels, dissipating as heat according to thermodynamic laws.",
            "notesSections": [
                {
                    "heading": "Energy Transfer and Ecological Pyramids",
                    "paragraphs": [
                        "Productivity: Gross Primary Productivity (GPP) is the total rate of biomass/organic matter synthesis during photosynthesis. Net Primary Productivity (NPP): NPP = GPP - R (where R is respiratory loss). NPP is the biomass available for consumption by heterotrophs.",
                        "Decomposition: Breakdown of complex organic detritus into inorganic raw materials (CO2, H2O, nutrients): (1) Fragmentation (earthworms break detritus into smaller particles); (2) Leaching (water-soluble inorganic nutrients seep into soil horizon); (3) Catabolism (bacterial and fungal enzymes degrade detritus); (4) Humification (leads to accumulation of dark amorphous colloidal humus, resistant to microbial action); (5) Mineralization (release of inorganic nutrients).",
                        "Energy Flow (Lindeman’s 10% Law): Only about 10% of the energy is transferred from one trophic level to the next higher level; 90% is lost as metabolic heat. Hence, food chains rarely exceed 4-5 trophic levels.",
                        "Ecological Pyramids: Pyramid of Energy is ALWAYS upright without exception, because energy is irreversibly lost as heat at each transfer. Pyramid of Numbers can be inverted (single oak tree supporting thousands of insects and birds). Pyramid of Biomass in sea is inverted (phytoplankton standing crop is smaller than zooplankton/fishes due to rapid turnover)."
                    ],
                    "keyTakeaways": [
                        "The annual net primary productivity of the whole biosphere is approximately 170 billion tons (dry weight) of organic matter, with oceans contributing only 55 billion tons despite occupying 70% of Earth's surface.",
                        "Humus is colloidal in nature and serves as an immense reservoir of nutrients."
                    ],
                    "examTips": ["The pyramid of energy is NEVER inverted under any circumstance because of the Second Law of Thermodynamics!"]
                }
            ],
            "misconceptions": ["Believing all ecological pyramids are upright. The pyramid of biomass in an aquatic ecosystem is INVERTED because phytoplankton have very small standing biomass at any given moment."],
            "formulas": [
                {
                    "label": "Net Primary Productivity & Lindeman’s 10% Law",
                    "formula": "\\text{NPP} = \\text{GPP} - R, \\quad E_{n+1} \\approx 0.10 \\times E_n \\quad (10\\% \\text{ Energy Trophic Efficiency})",
                    "description": "Formulas for net autotrophic biomass yield and inter-trophic thermodynamic energy transfer.",
                    "variables": [
                        { "symbol": "\\text{NPP}", "meaning": "Net Primary Productivity", "unit": "\\text{g}/(\\text{m}^2 \\text{yr})" },
                        { "symbol": "\\text{GPP}", "meaning": "Gross Primary Productivity", "unit": "\\text{g}/(\\text{m}^2 \\text{yr})" },
                        { "symbol": "R", "meaning": "Autotrophic Respiration Loss", "unit": "\\text{g}/(\\text{m}^2 \\text{yr})" },
                        { "symbol": "E_n", "meaning": "Trophic Level Energy", "unit": "\\text{kcal}" }
                    ]
                }
            ]
        }
    ],

    # BIO-12-13: Biodiversity and Conservation
    "BIO-12-13": [
        {
            "title": "Biodiversity Levels, Species-Area Relationship & Conservation",
            "desc": "Levels of biodiversity (genetic, species, ecological), latitudinal gradients in diversity, Alexander von Humboldt’s Species-Area relationship log S = log C + Z log A, Tilman’s long-term ecosystem stability, Paul Ehrlich’s 'Rivet Popper' hypothesis, causes of biodiversity loss ('The Evil Quartet': habitat loss/fragmentation, over-exploitation, alien species invasions, co-extinctions), and In-situ vs Ex-situ conservation.",
            "notesOverview": "Biodiversity represents biological variety across all organizational levels. Ecosystem stability depends on species richness. Anthropogenic pressures cause unprecedented biodiversity loss, requiring global in-situ and ex-situ conservation.",
            "notesSections": [
                {
                    "heading": "Species Richness Gradients and Conservation Strategies",
                    "paragraphs": [
                        "Levels of Biodiversity: Genetic (e.g. Rauwolfia vomitoria producing reserpine, 50,000 strains of rice, 1,000 varieties of mango); Species (amphibians have higher species diversity in Western Ghats than Eastern Ghats); Ecological (India has deserts, rain forests, mangroves, coral reefs, wetlands).",
                        "Latitudinal Gradients: Species diversity decreases from equator toward poles. Tropics harbor more species because: (1) Historically unglaciated, allowing long evolutionary time; (2) More constant, predictable environments reducing niche specialization; (3) Higher solar energy availability leading to higher productivity.",
                        "Species-Area Relationship (Alexander von Humboldt): On a logarithmic scale: log S = log C + Z log A (straight line with slope Z). For small regions Z = 0.1 to 0.2; for entire continents Z = 0.6 to 1.2 (frugivorous birds in tropical forests Z = 1.15).",
                        "The Evil Quartet (Causes of Extinction): (1) Habitat loss and fragmentation (most important cause: Amazon rainforest 'lungs of the planet' cut for soybeans and cattle); (2) Over-exploitation (Steller’s sea cow, passenger pigeon); (3) Alien species invasion (Nile perch in Lake Victoria caused extinction of 200 cichlid fish species; Parthenium, Eichhornia water hyacinth, African catfish Clarias gariepinus); (4) Co-extinctions (obligate mutualism).",
                        "Conservation Strategies: In-situ (on-site: 14 Biosphere Reserves, 90+ National Parks, 448+ Wildlife Sanctuaries, Sacred Groves like Khasi and Jaintia Hills in Meghalaya); Ex-situ (off-site: Zoological parks, Botanical gardens, Wildlife safari parks, Cryopreservation of gametes at -196 °C in liquid nitrogen, seed banks)."
                    ],
                    "keyTakeaways": [
                        "Sacred groves are traditional forest patches protected by indigenous communities due to religious beliefs, serving as last refuges for rare and threatened plants.",
                        "Biodiversity Hotspots: Regions with exceptionally high species richness and high degree of endemism (Western Ghats-Sri Lanka, Indo-Burma, Himalaya)."
                    ],
                    "examTips": ["Humboldt's Species-Area equation: S = C * A^Z. On a log-log scale it is a straight line: log S = log C + Z log A, where Z is the regression coefficient!"]
                }
            ],
            "misconceptions": ["Assuming botanical gardens and zoos are in-situ conservation. They are EX-SITU (off-site) conservation methods where endangered organisms are protected outside their natural habitats."],
            "formulas": [
                {
                    "label": "Humboldt’s Species-Area Relationship",
                    "formula": "S = C A^Z \\iff \\log_{10} S = \\log_{10} C + Z \\log_{10} A",
                    "description": "Power law relationship linking species richness S to geographical sampling area A.",
                    "variables": [
                        { "symbol": "S", "meaning": "Species Richness", "unit": "-" },
                        { "symbol": "A", "meaning": "Geographical Area", "unit": "\\text{km}^2" },
                        { "symbol": "Z", "meaning": "Regression Coefficient (Slope)", "unit": "-" },
                        { "symbol": "C", "meaning": "Y-Intercept Constant", "unit": "-" }
                    ]
                }
            ]
        }
    ]
}
